routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('students','StudentController');

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //
	protected $fillable = [
        'first_name', 'last_name', 'email','number','address','gender','status','image',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student as Student;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\File;

class StudentController extends Controller {

	public function create() {
		return view('create');
	}

	public function store(Request $request) {

		if ($request->hasfile('image')) {
			$file = $request->file('image');
			$name = time() . $file->getClientOriginalName();
			$file->move(public_path() . '/images/', $name);
		}

		$validator = Validator::make($request->all(), [
				'first_name' => 'required',
				'last_name' => 'required',
				'email' => 'required',
				'number' => 'max:255',
				'address' => 'required',
				'gender' => 'required',
		]);

		if ($validator->fails()) {
			return redirect()->back()
					->withErrors($validator)
					->withInput();
		}
		$student = new Student($request->all());
		$student->image = isset($name) ? $name : 'no image';
		$student->status = $request->get('status') ? $request->get('status') : 0;

		$student->save();
		return redirect('students')->with('success', 'Student added');
	}

	public function index() {
		$q = Input::get('q');
		$students = Student::where('first_name', 'LIKE', '%' . $q . '%')->orWhere('email', 'LIKE', '%' . $q . '%')->paginate(10);

		if (count($students) > 0) {
			return view('index', compact('students'))->withDetails($students)->withQuery($q);
		} else {
			return view('index', compact('students'))->withMessage('No Details found. Try to search again !');
		}
	}

	public function edit($id) {
		$student = student::find($id);
		return view('edit', compact('student', 'id'));
	}

	public function update(Request $request, $id) {

		$student = student::find($id);
		if (Input::hasFile('image')) {
			$usersImage = public_path("images/{$student->image}");
			if (File::exists($usersImage)) {
				unlink($usersImage);
			}
			$file = Input::file('image');
			$name = time() . '-' . $file->getClientOriginalName();
			$file->move(public_path() . '/images/', $name);
		}

		$student->first_name = $request->get('first_name');
		$student->last_name = $request->get('last_name');
		$student->email = $request->get('email');
		$student->number = $request->get('number');
		$student->address = $request->get('address');
		Input::hasFile('image') ? $student->image = $name : $student->image;
		$student->status = $request->get('status') ? $request->get('status') : 0;
		$student->save();
		return redirect('students')->with('success', 'Student  updated');
		
	}

	public function destroy($id) {
		$student = student::find($id);
		$student->delete();
		return redirect('students')->with('success', 'Student  deleted');
	}

	public function show($id) {
		$student = Student::find($id);
		return view('show', compact('student', 'id'));
	}

}

resources/views/create.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Student</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">  
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">  
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>  
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>  
  </head>
  <body>
    <div class="container">
      <h2>Create Student</h2><br/>
	  <a href="{{action('StudentController@index')}}" class="btn btn-primary">Home</a>
      <form method="post" action="{{url('students')}}" enctype="multipart/form-data">
		<input type="hidden" name="_token" value="{{ csrf_token() }}">      
		<div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4">
            <label for="First Name">First Name:</label>
            <input type="text" class="form-control" name="first_name" required>			
          </div>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
              <label for="Last Name">Last Name:</label>
              <input type="text" class="form-control" name="last_name" required>
            </div>
          </div>
        <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
              <label for="Email">Email:</label>
              <input type="email" class="form-control" name="email" required>
            </div>
          </div>

 <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
              <label for="Number">Number:</label>
              <input type="text" class="form-control" name="number" required>
            </div>
          </div>
		   <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
              <label for="Address">Address:</label>
              <input type="text" class="form-control" name="address" required>
            </div>
          </div>
		<div class="row">
			  <div class="col-md-4"></div>
			  <div class="form-group col-md-4">
				<input type="file" name="image">    
			 </div>
			</div>
      <div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <lable>Gender</lable>
				<input type="radio" id="sex" name="gender" value="female" />Female
				<input type="radio" id="sex" name="gender" value="male" />Male
            </div>
        </div>
	<div class="row">
          <div class="col-md-4"></div>
            <div class="form-group col-md-4">
                <lable>Status:</lable>
		 <input type="checkbox" name="status" id="status" value="1">Active
            </div>
        </div>
        </div>
        <div class="row">
          <div class="col-md-4"></div>
          <div class="form-group col-md-4" style="margin-top:60px">
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </body>
</html>

resources/views/edit.blade.php
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Update Student</title>
		<link rel="stylesheet" href="{{asset('css/app.css')}}">
	</head>
	<body>
		<div class="container">
			<h2>Update Student Details</h2><br  />
			<div class="pull-right">
                <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
            </div>
			<form method="post" action="{{action('StudentController@update', $id)}}" enctype="multipart/form-data">
				<input type="hidden" name="_token" value="{{ csrf_token() }}">      
				<input name="_method" type="hidden" value="PATCH">
				<div class="row">
					<div class="col-md-4"></div>
					<div class="form-group col-md-4">
						<label for="First Name">First Name:</label>
						<input type="text" class="form-control" name="first_name" value="{{$student->first_name}}" required>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4"></div>
					<div class="form-group col-md-4">
						<label for="Last Name">Last Name</label>
						<input type="text" class="form-control" name="last_name" value="{{$student->last_name}}" required>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4"></div>
					<div class="form-group col-md-4">
						<label for="Email">Email:</label>
						<input type="email" class="form-control" name="email" value="{{$student->email}}" required>
					</div>
				</div>
				<div class="row">
					<div class="col-md-4"></div>
					<div class="form-group col-md-4">
						<label for="Numebr">Number:</label>
						<input type="text" class="form-control" name="number" value="{{$student->number}}" required>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4"></div>
					<div class="form-group col-md-4">
						<label for="Address">Address:</label>
						<input type="text" class="form-control" name="address" value="{{$student->address}}" required>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4"></div>
					<div class="form-group col-md-4">
						<lable>Status:</lable>
						<?php
						if ($student->status == 1) {
							$checked = "checked";
						} else {
							$checked = '';
						}
						?>
						<input type="checkbox"  name="status" id="status" value="{{$student->status}}"  <?= $checked ?>>Active
					</div>
				</div>

				<div class="row">
					<div class="col-md-4"></div>
					<div class="form-group col-md-4">
						<img src="{{ asset('images/'.$student->image) }}" />
						<input type="file" name="image" > Upload New Picture   
					</div>
				</div>
				<div class="row">


					<div class="col-md-4"></div>
					<div class="form-group col-md-4" style="margin-top:60px">
						<button type="submit" class="btn btn-success" style="margin-left:38px">Update</button>
					</div>
				</div>
			</form>
		</div>
	</body>
</html>

resources/views/index.blade.php
	
<html>
  <head>
	   <script src="jquery-3.3.1.min.js"></script>
    <meta charset="utf-8">
    <title>Home</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
  </head>
  <body>
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script src="js/scripts.js"></script>
	 <form action="" method="get" role ="search" >
<input type="hidden" name="_token" value="{{ csrf_token() }}">      
    <div class="input-group">
        <input type="text" class="form-control" name="q" placeholder="Search students" value="{{(isset($_GET['q']) ? ($_GET['q']) : '')}}"> 
		<span class="input-group-btn">
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
            </button>
        </span>
    </div>
</form>
    <div class="container">
		 <br />
    @if (\Session::has('success'))
      <div class="alert alert-success">
        <p>{{ \Session::get('success') }}</p>
      </div><br />
     @endif
		 @if(isset($details))
    <br />
    <table class="table table-striped">
	<a href="{{action('StudentController@create')}}" class="btn btn-primary">Create Student</a>

    <thead>
      <tr>
        <th>ID</th>
        <th>First Name</th>
        <th>Last name</th>
        <th>Email</th>
        <th>Number</th>
        <th>Address</th>
        <th colspan="2">Action</th>
      </tr>
    </thead>
    <tbody>
      
      @foreach($details as $student)
      <tr>
        <td>{{$student['id']}}</td>
        <td>{{$student['first_name']}}</td>
        <td>{{$student['last_name']}}</td>
        <td>{{$student['email']}}</td>
        <td>{{$student['number']}}</td>
        <td>{{$student['address']}}</td>

        
		 <td><a href="{{action('StudentController@show', $student['id'])}}" class="btn btn-warning">View</a></td>
        <td><a href="{{action('StudentController@edit', $student['id'])}}" class="btn btn-warning">Edit</a></td>
        <td>
          <form class="delete"  action="{{action('StudentController@destroy', $student['id'])}}" method="post">
<input type="hidden" name="_token" value="{{ csrf_token() }}">      
            <input name="_method" type="hidden" value="DELETE">
            <button class="btn btn-danger" type="submit">Delete</button>
          </form>
        </td>
      </tr>
      @endforeach
	  <script>
    $(".delete").on("submit", function(){
        return confirm("Do you want to delete this item?");
    });
</script>
    </tbody>
  </table>
	     {{ $details->links() }}	
		 @endif
  </div>
  </body>
</html>

resources/views/search.blade.php
<div class="container">
    @if(isset($details))
        <p> The Search results for your query <b> {{ $query }} </b> are :</p>
    <h2>Sample User details</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            @foreach($details as $user)
            <tr>
                <td>{{$user->first_name}}</td>
                <td>{{$user->email}}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif
</div>

resources/views/show.blade.php
<head>
    <meta charset="utf-8">
    <title>Student Details</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
  </head>   
  <div class="center">
<div class="row">
        <div class="load">
            <div class="pull-left">
                <h2> Student Detail</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('students.index') }}"> Back</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="load">
            <div class="form-group">
                <strong>First Name:</strong>
                {{ $student->first_name}}
            </div>
        </div>
		<div class="load">
            <div class="form-group">
                <strong>Last Name:</strong>
                {{ $student->last_name}}
            </div>
        </div>
        <div class="load">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $student->email}}
            </div>
        </div>
		<div class="load">
            <div class="form-group">
                <strong>Number:</strong>
                {{ $student->number}}
            </div>
        </div>
		<div class="load">
            <div class="form-group">
                <strong>Address:</strong>
                {{ $student->address}}
            </div>
        </div>
		<div class="load">
            <div class="form-group">
                <strong>Gender:</strong>
                {{ $student->gender}}
            </div>
        </div>
		<div class="load">
            <div class="form-group">
                <strong>Student Picture:</strong>
		<img src="{{ asset('images/'.$student->image) }}" />
            </div>
        </div>
    </div>
</div>